# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_stack_models_uc/databricks-resources/*
# and mlops_stack_models_uc/bundle.yml with staging environment configs,
# when PRs are merged into the default branch
name: Bundle Deployment for mlops-stack-models-uc Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_stack_models_uc

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: mlops-stack-models-uc-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging Environment
        id: validate
        run: |
          databricks bundle validate -e staging
      - name: Deploy Bundle to Staging Environment
        id: deploy
        run: |
          databricks bundle deploy -e staging
